### start

GET http://{{host}}:{{port}}/driver/start/0001-0001

### stop

GET http://{{host}}:{{port}}/driver/stop/0001-0001

### start

POST http://{{host}}:{{port}}/driver/start/0001-0001
Content-Type: application/json

{ "name" : "name1"}

### start

POST http://{{host}}:{{port}}/driver/start/0001-0001
Content-Type: application/json

< ./start.json

### test

POST http://{{host}}:{{port}}/driver/test/0001-0001
Content-Type: application/json

< ./start.json

###
